### PR TITLE
add DEVELOP_MODE

### PR DESCRIPTION
**Pull request by hannikodo**
By default, the DEVELOP_MODE is OFF, program will access code under '/src'.
To use DEVELOP_MODE, add "-D DEVELOP_MODE=ON" when cmake, in which case the program will turn to '/dev'.

### CODE REVIEW

**Review by begoat — CHANGES_REQUESTED** [review]
Firstly, there is no need to have a /dev folder. You can just let the main.cpp to load `/src/QML/main.qml` when `DEVELOP_MODE=ON`

Secondly, `src/watchreload/watchreload.cpp` seems don't need `<iostream>` lib

**Review by sunnyadn — APPROVED** [review]

**Comment by begoat** [comment]
@hannikodo 
Two points need consider twice 
* in `src/main.cpp` file
It's not a good idea to use `DEVELOP_MODE == ON`(when cmake, using DEVELOP_MODE == OFF, and the app still load qtquickcontrols2.conf from local file system instead of in compiled qrc collection, which is unexpected) 
* in `src/watchreload/watchreload.cpp` file
the ErrorPage.qml is still loaded by the qrc file. when qrc is no used in DEVELOP_MODE, error will occur.(It's my fault and I will fix that later)

**Comment by begoat** [comment]
1. Your coding style is a bit far from that of Qt. Please read this doc as a reference.
for example: 
* in `src/main.cpp` keyword '+':  
**Always use a single space after a keyword (including non-standard keywords such as foreach) and before a curly brace** 
refer to https://github.com/Mogara/QSanguosha-For-Hegemony/wiki/Coding-Style for further information

* And redundancy in your code should be removed
for example `QString str` in `src/main.cpp`

* Some variables should be renamed to be more meaningful

2. Please leave some annotations when necessary in your code
for instance, the ENVIRONMENT_VARIABLE in main.cpp

**Comment by hannikodo** [comment]
fix some debugs

**Review by begoat — APPROVED** [review]

**Pull request merged**
